export const MODULE_NAME = 'COURSES_MODULE'

export const actionTypes = {
  GET_COURSES: `${MODULE_NAME}/GET_COURSES`,
  GET_COURSES_SUCCESS: `${MODULE_NAME}/GET_COURSES_SUCCESS`,
  GET_COURSES_FAILURE: `${MODULE_NAME}/GET_COURSES_FAILURE`,
}
