export const MODULE_NAME = 'AU_MODULE'

export const actionTypes = {
    ADD_NUBMER: `${MODULE_NAME}/ADD_NUBMER`,
    ADD_NUBMER_SUCCESS: `${MODULE_NAME}/ADD_NUBMER_SUCCESS`,
    ADD_NUBMER_FAILURE: `${MODULE_NAME}/ADD_NUBMER_FAILURE`,
}
